"""
Recommendation models for caching personalized recommendations.
"""

import uuid

from django.conf import settings
from django.db import models


class UserRecommendation(models.Model):
    """Cached recommendation for a user, generated by the recommendation engine."""

    REASON_CHOICES = [
        ("genre_match", "Based on your favorite genres"),
        ("author_match", "Based on authors you enjoy"),
        ("similar_readers", "Readers like you also enjoyed"),
        ("reading_history", "Based on your reading history"),
        ("trending", "Currently trending"),
        ("high_rated", "Highly rated in genres you like"),
        ("new_release", "New release in your preferred genres"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="recommendations",
    )
    book = models.ForeignKey(
        "books.Book",
        on_delete=models.CASCADE,
        related_name="recommendations",
    )
    score = models.FloatField(
        default=0.0,
        help_text="Recommendation confidence score (0-1).",
    )
    reason = models.CharField(
        max_length=20, choices=REASON_CHOICES, default="genre_match"
    )
    reason_detail = models.CharField(
        max_length=500,
        blank=True,
        help_text="Human-readable explanation for the recommendation.",
    )
    is_dismissed = models.BooleanField(
        default=False,
        help_text="User has dismissed this recommendation.",
    )
    is_clicked = models.BooleanField(default=False)
    clicked_at = models.DateTimeField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text="When this recommendation should be refreshed.",
    )

    class Meta:
        db_table = "user_recommendations"
        ordering = ["-score", "-created_at"]
        verbose_name = "User Recommendation"
        verbose_name_plural = "User Recommendations"
        unique_together = ["user", "book"]
        indexes = [
            models.Index(fields=["user", "-score"]),
            models.Index(fields=["user", "is_dismissed"]),
        ]

    def __str__(self):
        return (
            f"Recommend '{self.book.title}' to {self.user.email} "
            f"(score: {self.score:.2f})"
        )


class SimilarBook(models.Model):
    """Pre-computed similar book pairs for content-based recommendations."""

    book = models.ForeignKey(
        "books.Book",
        on_delete=models.CASCADE,
        related_name="similar_from",
    )
    similar_book = models.ForeignKey(
        "books.Book",
        on_delete=models.CASCADE,
        related_name="similar_to",
    )
    similarity_score = models.FloatField(
        default=0.0,
        help_text="Similarity score between the two books (0-1).",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "similar_books"
        ordering = ["-similarity_score"]
        unique_together = ["book", "similar_book"]
        verbose_name = "Similar Book"
        verbose_name_plural = "Similar Books"

    def __str__(self):
        return (
            f"'{self.book.title}' ~ '{self.similar_book.title}' "
            f"({self.similarity_score:.2f})"
        )
